# Generated by Django 5.0.7 on 2024-08-01 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wallimages',
            new_name='desktop_images',
        ),
    ]
