# Generated by Django 5.0.7 on 2024-08-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0002_rename_wallimages_desktop_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='mobile_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='wallpapers')),
            ],
            options={
                'db_table': 'mobile',
            },
        ),
        migrations.AlterModelTable(
            name='desktop_images',
            table='desktop',
        ),
    ]
