# Generated by Django 5.1 on 2024-08-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0004_desktop_images_type_mobile_images_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop_images',
            name='name',
            field=models.CharField(default='sample_data', max_length=50),
        ),
    ]
