# Generated by Django 5.1 on 2024-08-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0005_alter_desktop_images_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop_images',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
