# Generated by Django 5.1 on 2024-08-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0007_alter_desktop_images_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile_images',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
